mailman:
  hostname: mailman
  dbUrl:
    existingSecretName: db-app
    existingSecretKey: uri
  mailarchiver:
    apiKey:
      existingSecretName: mailman-mailarchive
      existingSecretKey: apiKey
    baseUrl:
      existingSecretName: mailman-mailarchive
      existingSecretKey: baseUrl
    destination:
      existingSecretName: mailman-mailarchive
      existingSecretKey: destination
  restApi:
    user:
      existingSecretName: mail-secrets-env
      existingSecretKey: mailmanApiUser
    pass:
      existingSecretName: mail-secrets-env
      existingSecretKey: mailmanApiPass

  mta: postfix
  smtpHost: postfix
  smtpPort: 25
  runners:
    archive:
      count: 1
    bounces:
      count: 1
    in:
      count: 1
    lmtp:
      count: 1
    out:
      count: 2
    pipeline:
      count: 1
    rest:
      count: 2
    retry:
      count: 1
      sleep_timer: 10s
    task:
      count: 1
    virgin:
      count: 1
    digest:
      count: 1
  arc:
    enabled: false
    domain: mydomain.com
    keyPath: /tmp/key
    selector: arc
    authserver_id: mydomain.com

#  MAILARCHIVE_API_KEY: c2FuZGJveC1hcGkta2V5LWZvci10ZXN0aW5nLW1haWxtYW4=
#  MAILARCHIVE_BASE_URL: aHR0cDovL21haWxhcmNoaXZlLXNhbmRib3gubGlzdHNlcnZlci5zdmMuY2x1c3Rlci5sb2NhbC9hcmNoLw==
#  MAILARCHIVE_DESTINATION: aHR0cDovL21haWxhcmNoaXZlLXNhbmRib3gubGlzdHNlcnZlci5zdmMuY2x1c3Rlci5sb2NhbC9hcGkvdjEvbWVzc2FnZS9pbXBvcnQv

dbSecret:
  create: false
  name: db-app
  data:
    uri: postgresql://user:pass@host:5432/dbName

mailarchiveSecret:
  create: false
  name: mailman-mailarchive
  data:
    apiKey: abcdE
    baseUrl: http://mailarchive/arch/
    destination: http://mailarchive/api/v1/message/import/

# Default values for mailman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/ietf-tools/container-mailman
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  apiPort: 8001
  lmtpPort: 8024

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  volumeName: ""
  annotations: {}
  # -- Only mount a subpath of the Volume into the pod
  subPath: ""

