{{- if .Values.dbSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecret.name }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}

type: Opaque
data:
  uri: {{ .Values.dbSecret.data.uri | b64enc }}
{{- end }}

