{{- if .Values.mailmanSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mailmanSecret.name }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}

type: Opaque
data:
  mailmanApiUser: {{ .Values.mailmanSecret.data.mailmanApiUser | b64enc }}
  mailmanApiPass: {{ .Values.mailmanSecret.data.mailmanApiPass | b64enc }}
{{- end }}
